---
server:
  port: ${APP_PORT:8080}
  timeZone: GMT
  servlet:
    context-path: /app-context

resteasy:
  jaxrs.app.registration: beans

spring:
  jersey:
    application-path: /jersey

management:
  endpoints:
    enabled-by-default: true
    web.exposure.include: health, metrics, info
    web.base-path: /actuator
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
      show-details: always
    metrics:
      enable: true